//! Compact instructions for trusted compile-time snippet programs. ASCII bytes 0..126
//! are literal; 127 escapes a byte, 128..254 name slots, and 255 extends a slot index.
//! Each input byte becomes at most two program bytes. Decoding advances monotonically:
//! no backreferences, allocation, recursion or client-supplied programs.
const std = @import("std");
pub const Token = union(enum) { literal: u8, index: u8 };
pub const Item = struct { start: usize, end: usize, token: Token };

pub fn literalSize(byte: u8) usize {
    return if (byte < 127) 1 else 2;
}

pub fn indexSize(value: u8) usize {
    std.debug.assert(value < 255);
    return if (value < 127) 1 else 2;
}

pub fn literal(output: []u8, byte: u8) usize {
    const size = literalSize(byte);
    std.debug.assert(output.len >= size);
    if (size == 1) output[0] = byte else output[0..2].* = .{ 127, byte };
    return size;
}

pub fn index(output: []u8, value: u8) usize {
    const size = indexSize(value);
    std.debug.assert(output.len >= size);
    if (size == 1) output[0] = 128 + value else output[0..2].* = .{ 255, value };
    return size;
}

/// Only compiler-generated bytes reach this reader; malformed programs are code defects.
pub fn next(bytes: []const u8, start: usize) ?Item {
    var cursor = start;
    while (cursor < bytes.len and bytes[cursor] < 127) : (cursor += 1) {}
    if (cursor == bytes.len) return null;
    const byte = bytes[cursor];
    if (byte != 127 and byte != 255)
        return .{ .start = cursor, .end = cursor + 1, .token = .{ .index = byte - 128 } };
    std.debug.assert(cursor + 1 < bytes.len);
    return .{
        .start = cursor,
        .end = cursor + 2,
        .token = if (byte == 127)
            .{ .literal = bytes[cursor + 1] }
        else
            .{ .index = bytes[cursor + 1] },
    };
}

test "snippet encoding roundtrips every literal byte and every supported instruction" {
    const t = std.testing;
    var source: [256]u8 = undefined;
    var encoded: [512]u8 = undefined;
    var length: usize = 0;
    for (&source, 0..) |*byte, i| {
        byte.* = @intCast(i);
        length += literal(encoded[length..], byte.*);
    }
    var decoded: [256]u8 = undefined;
    var writer: std.Io.Writer = .fixed(&decoded);
    var cursor: usize = 0;
    while (next(encoded[0..length], cursor)) |item| {
        try writer.writeAll(encoded[cursor..item.start]);
        try writer.writeByte(item.token.literal);
        cursor = item.end;
    }
    try writer.writeAll(encoded[cursor..length]);
    try t.expectEqualSlices(u8, &source, writer.buffered());
    for (0..255) |i| {
        const size = index(&encoded, @intCast(i));
        const item = next(encoded[0..size], 0).?;
        try t.expectEqual(@as(u8, @intCast(i)), item.token.index);
        try t.expectEqual(size, item.end);
    }
}
