const p = @import("console_protocol");
pub const Phase = enum {
    loading,
    setup,
    login,
    password,
    dashboard,
    geoip,
    security,
    events,
    challenges,
    similarity,
};
pub const State = struct {
    phase: Phase = .loading,
    navigation_open: bool = false,
    similarity: @import("similarity_state.zig").Model = .{},
    challenges: @import("challenges_page.zig").Model = .{},
    events: @import("events_state.zig").Model = .{},
    message: p.Bytes(256) = .{},
    username: p.Bytes(64) = .{},
    csrf: p.Bytes(64) = .{},
    role: p.Bytes(16) = .{},
    busy: bool = false,
    must_change: bool = false,
    totp_required: bool = false,
    stats_busy: bool = false,
    epoch: p.Bytes(32) = .{},
    sequence: u64 = 0,
    reconnect_ms: u32 = 1000,
    paused: bool = false,
    hidden: bool = false,
    browser_time: u64 = 0,
    received_at: u64 = 0,
    stale: bool = false,
    dark: bool = false,
    geometry: ?[]const u8 = null,
    geometry_busy: bool = false,
    geometry_retry_at: u64 = 0,
    globe: @import("geography.zig").View = .{},
    geo: p.geo.Metadata = .{},
    geo_status: p.Bytes(16) = .{},
    geo_progress: u32 = 0,
    geo_importing: bool = false,
    totp_available: bool = false,
    totp_enabled: bool = false,
    totp_revision: u64 = 0,
    totp_secret: p.Bytes(32) = .{},
    totp_uri: p.Bytes(134) = .{},
    recovery_codes: [10]p.Bytes(32) = @splat(.{}),
    recovery_count: usize = 0,
    stats: ?p.StatsSnapshot = null,
    points: [60]struct { second: u64 = 0, count: u64 = 0 } = @splat(.{}),

    pub fn fullAccess(self: *const State) bool {
        return self.csrf.len != 0 and !self.must_change and !self.totp_required;
    }
};
