#let sid-documents = (
  (
    number: "0001",
    slug: "sid-process",
    title: "The Shibuna Discussion Process and Engineering Standards",
    state: "published",
    area: "documentation",
    category: "Process Memo",
    status: "Published",
    created: "2026-09-07",
    updated: "2026-09-07",
    summary: "Defines the SID lifecycle, numbering workflow, TigerStyle engineering standards, structural code limits, and Elm-style diagnostic error reporting for the sibuna monorepo.",
    source: "docs/sid/records/0001-sid-process.typ",
    html: "sid/0001-sid-process.html",
    pdf: "pdf/sid-0001-sid-process.pdf",
  ),
  (
    number: "0002",
    slug: "sibuna-foundation-architecture",
    title: "Sibuna: Foundation Architecture, Delivery Plan, and Performance Contract",
    state: "published",
    area: "architecture",
    category: "Architectural Specification",
    status: "Published",
    created: "2026-09-07",
    updated: "2026-09-07",
    summary: "Foundational architectural specification, zero-allocation pipeline, two-tier proof-of-work engine, keyed-hash session tokens, product surfaces, measured performance contract, and delivery record for the Sibuna pure-Zig monorepo",
    source: "docs/sid/records/0002-sibuna-foundation-architecture.typ",
    html: "sid/0002-sibuna-foundation-architecture.html",
    pdf: "pdf/sid-0002-sibuna-foundation-architecture.pdf",
  ),
  (
    number: "0003",
    slug: "declarative-policy-engine",
    title: "Declarative Rule Policy Engine",
    state: "published",
    area: "policy",
    category: "Architectural Specification",
    status: "Published",
    created: "2026-09-07",
    updated: "2026-09-07",
    summary: "Specification of Sibuna's zero-allocation declarative rule engine: JSON policy files, multi-criteria matching over path, user agent, headers, and IPv4/IPv6 CIDRs, WEIGH scoring with thresholds, per-rule challenge parameters, the evaluation order, and dynamic policies replicated through Zaxonlite.",
    source: "docs/sid/records/0003-declarative-policy-engine.typ",
    html: "sid/0003-declarative-policy-engine.html",
    pdf: "pdf/sid-0003-declarative-policy-engine.pdf",
  ),
  (
    number: "0004",
    slug: "semantic-inspection",
    title: "Semantic Attack Inspection and GCRA Rate Limiting: The Shield Surface",
    state: "published",
    area: "security",
    category: "Architectural Specification",
    status: "Published",
    created: "2026-09-07",
    updated: "2026-09-07",
    summary: "Design and measured implementation of Sibuna's Shield surface: a single-pass tagged signature automaton, single-pass structural tokenizers for SQL injection, cross-site scripting, path traversal, and command injection, the byte-class pre-scan and canonicalisation gate, the GCRA rate limiter, the ban table, and incident recording.",
    source: "docs/sid/records/0004-semantic-inspection.typ",
    html: "sid/0004-semantic-inspection.html",
    pdf: "pdf/sid-0004-semantic-inspection.pdf",
  ),
  (
    number: "0005",
    slug: "zaxonlite-storage-architecture",
    title: "Distributed Storage Architecture: Zaxonlite Integration for Dynamic Policies, Replicated Reputation, and Incident Forensics",
    state: "published",
    area: "storage",
    category: "Architectural Specification",
    status: "Published",
    created: "2026-09-07",
    updated: "2026-09-07",
    summary: "Specifies and records the implementation of Sibuna's Edge surface: the embedded Zaxonlite store (replicated SQLite on paxos-zig) for cluster-wide dynamic policies, IP reputation, and forensic incident search, the read-copy-update engine slot that keeps the request path free of database access, the lock-free incident ring, and campaign clustering of attack payloads.",
    source: "docs/sid/records/0005-zaxonlite-storage-architecture.typ",
    html: "sid/0005-zaxonlite-storage-architecture.html",
    pdf: "pdf/sid-0005-zaxonlite-storage-architecture.pdf",
  ),
  (
    number: "0006",
    slug: "mathematical-foundations",
    title: "Mathematical Foundations of Sibuna: Sequential Work, Symmetric Authentication, Bounded State, and Linear-Time Inspection",
    state: "published",
    area: "cryptography",
    category: "Architectural Specification",
    status: "Published",
    created: "2026-09-07",
    updated: "2026-09-07",
    summary: "A paper-style record of the mathematics behind every Sibuna hot-path primitive: the Cohen–Pietrzak proof of sequential work and the geometric hashcash tier, keyed-hash tokens and stateless challenges with work-bounded state, GCRA rate limiting, Robin Hood spent sets, Aho–Corasick and single-pass tokenizers for inspection, read-copy-update engine slots, adaptive difficulty, and feature-hashed campaign clustering, each with definitions, lemmas, proofs, citations, and the exact pure-Zig implementation and measurement that realises it.",
    source: "docs/sid/records/0006-mathematical-foundations.typ",
    html: "sid/0006-mathematical-foundations.html",
    pdf: "pdf/sid-0006-mathematical-foundations.pdf",
  ),
  (
    number: "0007",
    slug: "console-management-interface",
    title: "The Sibuna Console: A Real-Time Management Interface for Nodes and Clusters",
    state: "committed",
    area: "console",
    category: "Architectural Specification",
    status: "Committed",
    created: "2026-09-08",
    updated: "2026-10-02",
    summary: "Specifies the Sibuna Console, a complete management interface: a management module started from the Sibuna CLI, serving a real-time web interface over HTTP and WebSockets, rendering pages from a WebAssembly module styled with daisyUI 5, keeping users, sessions, audit, minute statistics, and a GeoIP database in the embedded Zaxonlite store, managing one node or a cluster, with explicit isolation targets and inconclusive container measurements, an authenticated live GeoIP globe dashboard, complete route wireframes, resolved design decisions, protocol, data model, build pipeline, and delivery plan.",
    source: "docs/sid/records/0007-console-management-interface.typ",
    html: "sid/0007-console-management-interface.html",
    pdf: "pdf/sid-0007-console-management-interface.pdf",
  ),
  (
    number: "0008",
    slug: "ai-bot-traffic-monitoring",
    title: "AI Bot Traffic Identification, Multi-Tier Verification, and Operator Console Analytics",
    state: "discussion",
    area: "analytics",
    category: "Architectural Specification",
    status: "Open for Discussion",
    created: "2026-09-15",
    updated: "2026-09-15",
    summary: "Specifies the architecture for identifying, verifying, and monitoring AI crawler and automated bot traffic in Sibuna: zero-allocation single-pass signature matching, sub-microsecond Radix CIDR verification for major providers (OpenAI, Anthropic, Google Gemini, Perplexity, Meta, Apple, ByteDance), multi-tier confidence classification, bounded telemetry extensions, and a real-time console dashboard delivering visual composition, time-series analysis, and granular tabular analytics contrasting bot traffic against actual human traffic.",
    source: "docs/sid/records/0008-ai-bot-traffic-monitoring.typ",
    html: "sid/0008-ai-bot-traffic-monitoring.html",
    pdf: "pdf/sid-0008-ai-bot-traffic-monitoring.pdf",
  ),
  (
    number: "0009",
    slug: "chunked-request-bodies",
    title: "Chunked Request Bodies: Strict In-Place Decoding, Canonical Re-Framing, and Inspection Equivalence",
    state: "committed",
    area: "http",
    category: "Architectural Specification",
    status: "Committed",
    created: "2026-10-02",
    updated: "2026-10-02",
    summary: "Specifies how the reverse proxy accepts chunked request bodies without a heap allocation or a second buffer: a strict RFC 9112 chunk grammar that rejects every known terminator and extension ambiguity, an in-place decoder whose output never overtakes its input, Content-Length forwarding for bodies that complete within the connection buffer and canonical re-chunking for the rest, and proofs that inspection sees exactly the bytes a Content-Length request would show and that the origin cannot observe the client's framing.",
    source: "docs/sid/records/0009-chunked-request-bodies.typ",
    html: "sid/0009-chunked-request-bodies.html",
    pdf: "pdf/sid-0009-chunked-request-bodies.pdf",
  ),
)
