//! Every API route declares its authentication boundary and minimum application action.
//! Account routes remain usable during required password changes and TOTP enrollment.
const std = @import("std");
const p = @import("console_protocol");
pub const Access = enum { public, account, full };
pub const Handler = enum {
    crs_status,
    crs_test,
    crs_test_read,
    crs_test_details,
    crs_review,
    crs_review_read,
    crs_exclusions,
    crs_prepare,
    crs_select,
    crs_discard,
    crs_configuration,
    challenge_summary,
    challenge_records,
    challenge_difficulty,
    node_status,
    nodes_members,
    node_command,
    node_command_read,
    audit_query,
    audit_read,
    audit_export,
    tokens_query,
    tokens_create,
    tokens_revoke,
    users_query,
    users_create,
    users_change,
    policies,
    policies_test,
    policy_edit,
    inspection_edit,
    policy_read,
    setup_status,
    login,
    session,
    logout,
    password,
    stats,
    timeline,
    minutes,
    minute_summary,
    rankings,
    ranking_history,
    rule_hit_history,
    challenges,
    events,
    events_similar,
    events_export,
    events_heads,
    events_crs,
    security_query,
    security_trends,
    stream,
    peer,
    geoip,
    totp,
    kiosk_token,
    kiosk_exchange,
    settings_query,
    settings_change,
    notifications_query,
    notifications_save,
    notifications_remove,
    notifications_test,
    pages_read,
    pages_edit,
    pages_preview,
    pages_preview_get,
    policy_order,
    policy_replay,
    reputation_query,
    reputation_edit,
    reputation_remove,
    country_preview,
    country_apply,
    import_chunk,
    import_commit,
    about,
};
pub const Route = struct {
    path: []const u8,
    method: std.http.Method,
    access: Access,
    action: p.Action = .read,
    token_scope: ?p.tokens.Scope = null,
    // Administrator-only reads do not consume the management mutation allowance.
    mutation: bool = false,
    // Read-only kiosk sessions may reach only the routes that opt in.
    kiosk: bool = false,
    handler: Handler,
};
const table = [_]Route{
    .{
        .path = "/console/api/crs/review/exclusions",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_exclusions,
    },
    .{
        .path = "/console/api/crs/review",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_review,
    },
    .{
        .path = "/console/api/crs/review/result",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_review_read,
    },
    .{
        .path = "/console/api/crs/status",
        .method = .GET,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_status,
        .mutation = false,
    },
    .{
        .path = "/console/api/crs/configuration",
        .method = .GET,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_configuration,
        .mutation = false,
    },
    .{
        .path = "/console/api/crs/test",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_test,
        .mutation = true,
    },
    .{
        .path = "/console/api/crs/test/details",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_test_details,
    },
    .{
        .path = "/console/api/crs/test/result",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_test_read,
    },
    .{
        .path = "/console/api/crs/prepare",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_prepare,
        .mutation = true,
    },
    .{
        .path = "/console/api/crs/select",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_select,
        .mutation = true,
    },
    .{
        .path = "/console/api/crs/discard",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .crs_discard,
        .mutation = true,
    },
    .{ .path = "/console/peer", .method = .GET, .access = .public, .handler = .peer },
    .{
        .path = "/console/api/nodes/local",
        .method = .GET,
        .access = .full,
        .handler = .node_status,
    },
    .{
        .path = "/console/api/nodes",
        .method = .GET,
        .access = .full,
        .token_scope = .stats_read,
        .handler = .nodes_members,
    },
    .{
        .path = "/console/api/nodes/command",
        .method = .POST,
        .access = .full,
        .action = .control_node,
        .handler = .node_command,
        .mutation = true,
    },
    .{
        .path = "/console/api/nodes/command/read",
        .method = .POST,
        .access = .full,
        .handler = .node_command_read,
    },
    .{
        .path = "/console/api/audit/query",
        .method = .POST,
        .access = .full,
        .handler = .audit_query,
    },
    .{
        .path = "/console/api/audit/read",
        .method = .POST,
        .access = .full,
        .handler = .audit_read,
    },
    .{
        .path = "/console/api/audit/export",
        .method = .POST,
        .access = .full,
        .handler = .audit_export,
    },

    .{
        .path = "/console/api/tokens/query",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .tokens_query,
    },
    .{
        .path = "/console/api/tokens/create",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .tokens_create,
        .mutation = true,
    },
    .{
        .path = "/console/api/tokens/revoke",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .tokens_revoke,
        .mutation = true,
    },
    .{
        .path = "/console/api/users/query",
        .method = .POST,
        .access = .full,
        .handler = .users_query,
        .token_scope = .users_read,
    },
    .{
        .path = "/console/api/users/create",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .users_create,
        .mutation = true,
        .token_scope = .users_write,
    },
    .{
        .path = "/console/api/users/change",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .users_change,
        .mutation = true,
        .token_scope = .users_write,
    },
    .{
        .path = "/console/api/minutes",
        .method = .POST,
        .access = .full,
        .handler = .minutes,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/minutes/summary",
        .method = .POST,
        .access = .full,
        .handler = .minute_summary,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/timeline",
        .method = .POST,
        .access = .full,
        .kiosk = true,
        .handler = .timeline,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/inspection/edit",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .inspection_edit,
        .mutation = true,
        .token_scope = .policy_write,
    },
    .{
        .path = "/console/api/policies/hits",
        .method = .POST,
        .access = .full,
        .handler = .rule_hit_history,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/rankings/history",
        .method = .POST,
        .access = .full,
        .handler = .ranking_history,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/rankings/query",
        .method = .POST,
        .access = .full,
        .handler = .rankings,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/rankings",
        .method = .GET,
        .access = .full,
        .handler = .rankings,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/policies/read",
        .method = .POST,
        .access = .full,
        .handler = .policy_read,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/policies/edit",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .policy_edit,
        .mutation = true,
        .token_scope = .policy_write,
    },
    .{
        .path = "/console/api/policies/query",
        .method = .POST,
        .access = .full,
        .handler = .policies,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/policies/test",
        .method = .POST,
        .access = .full,
        .handler = .policies_test,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/security/trends",
        .method = .POST,
        .access = .full,
        .handler = .security_trends,
        .token_scope = .stats_read,
        .kiosk = true,
    },
    .{
        .path = "/console/api/security/query",
        .method = .POST,
        .access = .full,
        .handler = .security_query,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/events/similar",
        .method = .POST,
        .access = .full,
        .handler = .events_similar,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/events/heads",
        .method = .POST,
        .access = .full,
        .handler = .events_heads,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/events/crs",
        .method = .POST,
        .access = .full,
        .handler = .events_crs,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/challenges",
        .method = .POST,
        .access = .full,
        .handler = .challenges,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/challenges/summary",
        .method = .POST,
        .access = .full,
        .handler = .challenge_summary,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/challenges/records",
        .method = .POST,
        .access = .full,
        .handler = .challenge_records,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/challenges/difficulty",
        .method = .POST,
        .access = .full,
        .handler = .challenge_difficulty,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/events/export",
        .method = .POST,
        .access = .full,
        .handler = .events_export,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/events/query",
        .method = .POST,
        .access = .full,
        .handler = .events,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/settings/query",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .settings_query,
    },
    .{
        .path = "/console/api/settings/change",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .settings_change,
        .mutation = true,
    },
    .{
        .path = "/console/api/notifications/query",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .notifications_query,
    },
    .{
        .path = "/console/api/notifications/save",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .notifications_save,
        .mutation = true,
    },
    .{
        .path = "/console/api/notifications/remove",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .notifications_remove,
        .mutation = true,
    },
    .{
        .path = "/console/api/notifications/test",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .notifications_test,
        .mutation = true,
    },
    .{
        .path = "/console/api/policies/order",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .policy_order,
        .token_scope = .policy_write,
        .mutation = true,
    },
    .{
        .path = "/console/api/policies/replay",
        .method = .POST,
        .access = .full,
        .action = .read,
        .handler = .policy_replay,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/reputation/query",
        .method = .POST,
        .access = .full,
        .action = .read,
        .handler = .reputation_query,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/reputation/edit",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .reputation_edit,
        .token_scope = .policy_write,
        .mutation = true,
    },
    .{
        .path = "/console/api/reputation/remove",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .reputation_remove,
        .token_scope = .policy_write,
        .mutation = true,
    },
    .{
        .path = "/console/api/geoip/country/preview",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .country_preview,
        .token_scope = .policy_write,
    },
    .{
        .path = "/console/api/geoip/country/apply",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .country_apply,
        .token_scope = .policy_write,
        .mutation = true,
    },
    .{
        .path = "/console/api/policies/import/chunk",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .import_chunk,
        .token_scope = .policy_write,
    },
    .{
        .path = "/console/api/policies/import/commit",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .import_commit,
        .token_scope = .policy_write,
        .mutation = true,
    },
    .{
        .path = "/console/api/pages/read",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .pages_read,
    },
    .{
        .path = "/console/api/pages/edit",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .pages_edit,
        .mutation = true,
    },
    .{
        .path = "/console/api/pages/preview",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .pages_preview,
        .mutation = true,
    },
    .{
        .path = "/console/api/pages/preview/challenge",
        .method = .GET,
        .access = .full,
        .action = .manage_settings,
        .handler = .pages_preview_get,
    },
    .{
        .path = "/console/api/pages/preview/denied",
        .method = .GET,
        .access = .full,
        .action = .manage_settings,
        .handler = .pages_preview_get,
    },
    .{
        .path = "/console/api/pages/preview/rate_limited",
        .method = .GET,
        .access = .full,
        .action = .manage_settings,
        .handler = .pages_preview_get,
    },
    .{
        .path = "/console/api/pages/preview/banned",
        .method = .GET,
        .access = .full,
        .action = .manage_settings,
        .handler = .pages_preview_get,
    },
    .{
        .path = "/console/api/pages/preview/overloaded",
        .method = .GET,
        .access = .full,
        .action = .manage_settings,
        .handler = .pages_preview_get,
    },
    .{
        .path = "/console/api/kiosk/token",
        .method = .POST,
        .access = .full,
        .action = .open_kiosk,
        .handler = .kiosk_token,
        .mutation = true,
    },
    .{
        .path = "/console/api/kiosk/exchange",
        .method = .POST,
        .access = .public,
        .handler = .kiosk_exchange,
    },
    .{
        .path = "/console/api/setup",
        .method = .GET,
        .access = .public,
        .handler = .setup_status,
    },
    .{
        .path = "/console/api/login",
        .method = .POST,
        .access = .public,
        .handler = .login,
    },
    .{
        .path = "/console/api/session",
        .method = .GET,
        .access = .account,
        .kiosk = true,
        .handler = .session,
    },
    .{
        .path = "/console/api/about",
        .method = .GET,
        .access = .full,
        .action = .manage_settings,
        .handler = .about,
    },
    .{
        .path = "/console/api/logout",
        .method = .POST,
        .access = .account,
        .kiosk = true,
        .handler = .logout,
    },
    .{
        .path = "/console/api/password",
        .method = .POST,
        .access = .account,
        .handler = .password,
    },
    .{
        .path = "/console/api/stats",
        .method = .GET,
        .access = .full,
        .kiosk = true,
        .handler = .stats,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/ws",
        .method = .GET,
        .access = .full,
        .kiosk = true,
        .handler = .stream,
    },
    .{
        .path = "/console/stream",
        .method = .GET,
        .access = .full,
        .kiosk = true,
        .handler = .stream,
    },
    .{
        .path = "/console/api/geoip",
        .method = .GET,
        .access = .full,
        .handler = .geoip,
        .token_scope = .geoip_read,
    },
    .{
        .path = "/console/api/geoip",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .geoip,
        .token_scope = .geoip_write,
        .mutation = true,
    },
    .{
        .path = "/console/api/totp",
        .method = .GET,
        .access = .account,
        .handler = .totp,
    },
    .{
        .path = "/console/api/totp/enroll",
        .method = .POST,
        .access = .account,
        .handler = .totp,
    },
    .{
        .path = "/console/api/totp/confirm",
        .method = .POST,
        .access = .account,
        .handler = .totp,
    },
};

pub fn find(path: []const u8, method: std.http.Method) ?Route {
    for (table) |route| {
        if (route.method == method and std.mem.eql(u8, route.path, path)) return route;
    }
    return null;
}
