//! Every API route declares its authentication boundary and minimum application action.
//! Account routes remain usable during required password changes and TOTP enrollment.
const std = @import("std");
const p = @import("console_protocol");
pub const Access = enum { public, account, full };
pub const Handler = enum {
    node_status,
    node_command,
    node_command_read,
    audit_query,
    audit_read,
    audit_export,
    tokens_query,
    tokens_create,
    tokens_revoke,
    users_query,
    users_create,
    users_change,
    policies,
    policies_test,
    policy_edit,
    inspection_edit,
    policy_read,
    setup_status,
    login,
    session,
    logout,
    password,
    stats,
    timeline,
    minutes,
    rankings,
    challenges,
    events,
    events_similar,
    events_export,
    stream,
    geoip,
    totp,
};
pub const Route = struct {
    path: []const u8,
    method: std.http.Method,
    access: Access,
    action: p.Action = .read,
    token_scope: ?p.tokens.Scope = null,
    // Administrator-only reads do not consume the management mutation allowance.
    mutation: bool = false,
    handler: Handler,
};
const table = [_]Route{
    .{
        .path = "/console/api/nodes/local",
        .method = .GET,
        .access = .full,
        .handler = .node_status,
    },
    .{
        .path = "/console/api/nodes/command",
        .method = .POST,
        .access = .full,
        .action = .control_node,
        .handler = .node_command,
        .mutation = true,
    },
    .{
        .path = "/console/api/nodes/command/read",
        .method = .POST,
        .access = .full,
        .handler = .node_command_read,
    },
    .{
        .path = "/console/api/audit/query",
        .method = .POST,
        .access = .full,
        .handler = .audit_query,
    },
    .{
        .path = "/console/api/audit/read",
        .method = .POST,
        .access = .full,
        .handler = .audit_read,
    },
    .{
        .path = "/console/api/audit/export",
        .method = .POST,
        .access = .full,
        .handler = .audit_export,
    },

    .{
        .path = "/console/api/tokens/query",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .tokens_query,
    },
    .{
        .path = "/console/api/tokens/create",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .tokens_create,
        .mutation = true,
    },
    .{
        .path = "/console/api/tokens/revoke",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .tokens_revoke,
        .mutation = true,
    },
    .{
        .path = "/console/api/users/query",
        .method = .POST,
        .access = .full,
        .handler = .users_query,
        .token_scope = .users_read,
    },
    .{
        .path = "/console/api/users/create",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .users_create,
        .mutation = true,
        .token_scope = .users_write,
    },
    .{
        .path = "/console/api/users/change",
        .method = .POST,
        .access = .full,
        .action = .manage_users,
        .handler = .users_change,
        .mutation = true,
        .token_scope = .users_write,
    },
    .{
        .path = "/console/api/minutes",
        .method = .POST,
        .access = .full,
        .handler = .minutes,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/timeline",
        .method = .POST,
        .access = .full,
        .handler = .timeline,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/inspection/edit",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .inspection_edit,
        .mutation = true,
        .token_scope = .policy_write,
    },
    .{
        .path = "/console/api/rankings",
        .method = .GET,
        .access = .full,
        .handler = .rankings,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/policies/read",
        .method = .POST,
        .access = .full,
        .handler = .policy_read,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/policies/edit",
        .method = .POST,
        .access = .full,
        .action = .manage_policy,
        .handler = .policy_edit,
        .mutation = true,
        .token_scope = .policy_write,
    },
    .{
        .path = "/console/api/policies/query",
        .method = .POST,
        .access = .full,
        .handler = .policies,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/policies/test",
        .method = .POST,
        .access = .full,
        .handler = .policies_test,
        .token_scope = .policy_read,
    },
    .{
        .path = "/console/api/events/similar",
        .method = .POST,
        .access = .full,
        .handler = .events_similar,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/challenges",
        .method = .POST,
        .access = .full,
        .handler = .challenges,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/api/events/export",
        .method = .POST,
        .access = .full,
        .handler = .events_export,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/events/query",
        .method = .POST,
        .access = .full,
        .handler = .events,
        .token_scope = .events_read,
    },
    .{
        .path = "/console/api/setup",
        .method = .GET,
        .access = .public,
        .handler = .setup_status,
    },
    .{
        .path = "/console/api/login",
        .method = .POST,
        .access = .public,
        .handler = .login,
    },
    .{
        .path = "/console/api/session",
        .method = .GET,
        .access = .account,
        .handler = .session,
    },
    .{
        .path = "/console/api/logout",
        .method = .POST,
        .access = .account,
        .handler = .logout,
    },
    .{
        .path = "/console/api/password",
        .method = .POST,
        .access = .account,
        .handler = .password,
    },
    .{
        .path = "/console/api/stats",
        .method = .GET,
        .access = .full,
        .handler = .stats,
        .token_scope = .stats_read,
    },
    .{
        .path = "/console/stream",
        .method = .GET,
        .access = .full,
        .handler = .stream,
    },
    .{
        .path = "/console/api/geoip",
        .method = .GET,
        .access = .full,
        .handler = .geoip,
        .token_scope = .geoip_read,
    },
    .{
        .path = "/console/api/geoip",
        .method = .POST,
        .access = .full,
        .action = .manage_settings,
        .handler = .geoip,
        .token_scope = .geoip_write,
        .mutation = true,
    },
    .{
        .path = "/console/api/totp",
        .method = .GET,
        .access = .account,
        .handler = .totp,
    },
    .{
        .path = "/console/api/totp/enroll",
        .method = .POST,
        .access = .account,
        .handler = .totp,
    },
    .{
        .path = "/console/api/totp/confirm",
        .method = .POST,
        .access = .account,
        .handler = .totp,
    },
};

pub fn find(path: []const u8, method: std.http.Method) ?Route {
    for (table) |route| {
        if (route.method == method and std.mem.eql(u8, route.path, path)) return route;
    }
    return null;
}
