#let shd-documents = (
  (
    number: "0001",
    slug: "shd-process",
    title: "The Shibuna Discussion Process and Engineering Standards",
    state: "published",
    area: "documentation",
    category: "Process Memo",
    status: "Published",
    created: "2026-09-07",
    updated: "2026-09-07",
    summary: "Defines the SHD lifecycle, numbering workflow, TigerStyle engineering standards, structural code limits, and Elm-style diagnostic error reporting for the sibuna monorepo.",
    source: "docs/shd/records/0001-shd-process.typ",
    html: "shd/0001-shd-process.html",
    pdf: "pdf/shd-0001-shd-process.pdf",
  ),
  (
    number: "0002",
    slug: "sibuna-foundation-architecture",
    title: "Sibuna: Foundation Architecture, Delivery Plan, and Performance Contract",
    state: "published",
    area: "architecture",
    category: "Architectural Specification",
    status: "Published",
    created: "2026-09-07",
    updated: "2026-09-07",
    summary: "Foundational architectural specification, Anubis comparative analysis, zero-allocation pipeline, native SIMD PoW verification, pure Zig browser WASM solver, and product delivery plan for the Sibuna pure-Zig monorepo.",
    source: "docs/shd/records/0002-sibuna-foundation-architecture.typ",
    html: "shd/0002-sibuna-foundation-architecture.html",
    pdf: "pdf/shd-0002-sibuna-foundation-architecture.pdf",
  ),
)
